version: '3.8'
services:
  frontend:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - lakay-net

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    working_dir: /app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=4001
    depends_on:
      - db
    command: sh -c "npm run migrate && npm start"
    networks:
      - lakay-net

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: lakaydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lakay-net

volumes:
  pgdata:

networks:
  lakay-net:
    driver: bridge
